version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./hostbuddy.db
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=10080
      - MINIO_ENDPOINT=minio:9000
      - MINIO_PUBLIC_ENDPOINT=localhost:9000
      - MINIO_ACCESS_KEY=hostbuddy
      - MINIO_SECRET_KEY=hostbuddy123
      - MINIO_BUCKET=images
      - MINIO_SECURE=false
    depends_on:
      - minio
    volumes:
      - .:/app
      - ./hostbuddy.db:/app/hostbuddy.db  # Mount SQLite database file
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API endpoint
      - "9001:9001"  # Console UI
    environment:
      - MINIO_ROOT_USER=hostbuddy
      - MINIO_ROOT_PASSWORD=hostbuddy123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  minio_data: