version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://hostbuddy:hostbuddy123@db:5432/hostbuddy
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - MINIO_ENDPOINT=minio:9000
      - MINIO_PUBLIC_ENDPOINT=localhost:9000
      - MINIO_ACCESS_KEY=hostbuddy
      - MINIO_SECRET_KEY=hostbuddy123
      - MINIO_BUCKET=images
      - MINIO_SECURE=false
    depends_on:
      - db
      - minio
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=hostbuddy
      - POSTGRES_PASSWORD=hostbuddy123
      - POSTGRES_DB=hostbuddy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API endpoint
      - "9001:9001"  # Console UI
    environment:
      - MINIO_ROOT_USER=hostbuddy
      - MINIO_ROOT_PASSWORD=hostbuddy123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data: